# Config definition
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 1.Data General Setting. Can be replaced in respective sets
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
DATA:
 DATASETS:
  NAMES: ('ddr_DRgrading')#('cifa10')#('ddr_DRgrading')#('imagenet')
  ROOT_DIR: ('./data')

 DATALOADER:
  NUM_WORKERS: 1
  SAMPLER: 'softmax_rank'#'ranked_loss'#
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 2
  IMS_PER_BATCH: 24

 TRANSFORM:
  SIZE: [224, 224]#[736, 736]#[640,640]#[224, 224]#[512, 512]
  MASK_SIZE_RATIO: 1
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PADDING: 8

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 2.Model General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
MODEL:
 DEVICE: "cuda"
 #DEVICE_ID: '0'
 NAME: 'densenet121'                                         #'densenet121'#'mbagnet121' 
 PRE_ACTIVATION: 1
 FUSION_TYPE: 'concat'                                        #"concat","add","none"
 BASE_CLASSIFIER_COMBINE_TYPE: "f-c"            #"f-c","pl-c","fl-n"

 # "none", "weakSu-segRe", "strongSu-segRe", "jointSu-segRe", "strongSu-gcamRe", "noneSu-gcamRe", 
 BRANCH_CONFIG_TYPE: "noneSu-gcamRe"                       
 BRANCH_IMG_NUM: 2
 #(1). Segmentation Branch
 HOOK_TYPE:  "featureReserve"                           #"featureReserve","rflogitGenerate","none" 
 SEGMENTATION_TYPE:  "denseFC"                     #"denseFC", "bagFeature", "none" 
 SEG_NUM_CLASSES: 4
 SEG_SUPERVISED_TYPE: "strong"
 #(2). Grad-CAM Branch
 GRAD_CAM_TYPE: "none"                                   #"none", "supervise_seg", "reload"
 #(3). Reload Branch
 MASKED_IMG_RELOAD_TYPE: "none"                 #"none", "seg_mask", "gradcam_mask" 
 

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 3.LOSS General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
LOSS:
 TYPE: 'cross_entropy_loss seg_mask_loss gcam_mask_loss pos_masked_img_loss neg_masked_img_loss for_show_loss' # 
 MARGIN_RANK: 1.3 ### R: ALPHA - MARGIN_RANK
 ALPHA: 2.0
 TVAL: 1.0
 WEIGHT: 0.4    ### loss: softmax + w*ranked_loss


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 4.Solver
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
SOLVER:
 MAX_EPOCHS: 100
 EVAL_PERIOD: 1
 CHECKPOINT_PERIOD: 1
 LOG_PERIOD: 10
 OUTPUT_DIR: "work_space" 

 # OPTIMIZER configuration
 OPTIMIZER:
  NAME: "Adam"#"SGD"#
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.

 # SCHEDULER configuration
 SCHEDULER:
  BASE_LR: 0.0001#0.001#0.00001#0.0001
  BIAS_LR_FACTOR: 1
  GAMMA: 0.1
  STEPS: [10, 20, 60]#[10, 15, 20]#[3, 6, 9]# [50, 75, 100] #[50, 100, 150]#
  WARMUP_FACTOR: 0.33
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
  LOSS_LR: 0.05
  RETRAIN_FROM_HEAD: 1


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Train Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TRAIN:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Train Transform
 TRANSFORM:
  PROB: 0.0
  RE_PROB: 0.0

 # Train Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 4
  INSTANCES_PER_CATEGORY_IN_BATCH: 1#2
  MASK_PER_BATCH: 1
  ACCUMULATION_STEP: 1

 # Train Trick
 TRICK:
  PRETRAIN_PATH: './pretrained/densenet121-a639ec97.pth'  #'./pretrained/densenet201-c1103571.pth'
  IF_LABELSMOOTH: 'off'#'on'
  PRETRAINED: 1


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Val Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
VAL:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Val Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 3
  INSTANCES_PER_CATEGORY_IN_BATCH: 1#1
  MASK_PER_BATCH: 1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Test Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TEST:
 RE_RANKING: 'no'
 WEIGHT: "./work_space/densenet121_model_1.pth"
 FEAT_NORM: 'yes'

 # Test Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 3
  INSTANCES_PER_CATEGORY_IN_BATCH: 1#3
  MASK_PER_BATCH: 1