# Config definition
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 1.Data General Setting. Can be replaced in respective sets
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
DATA:
 DATASETS:
  NAMES: ('ddr_DRgrading')#('cifa10')#('ddr_DRgrading')#('imagenet')
  ROOT_DIR: ('./data')

 DATALOADER:
  NUM_WORKERS: 4
  SAMPLER: 'softmax_rank'#'ranked_loss'#
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 2
  IMS_PER_BATCH: 24

 TRANSFORM:
  SIZE: [224, 224]#[736, 736]#[640,640]#[224, 224]#[512, 512]
  MASK_SIZE_RATIO: 4
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PADDING: 10

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 2.Model General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
MODEL:
 DEVICE: "cuda"
 #DEVICE_ID: '0'
 NAME: 'mbagnet121'#'mbagnet121'#'multi_bagnet'#'densenetS224'#'bagnet'#'densenet121'#'resnet50'##'resnet50'#_ibn_a'
 PRE_ACTIVATION: 1
 FUSION_TYPE: 'concat'

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 3.LOSS General Setting. Can be replaced in respective sets Structure Information
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
LOSS:
 TYPE: 'cross_entropy_loss mask_loss'# 'cross_entropy_multilabel_loss'#'cross_entropy_loss'# margin_loss similarity_loss'#'cross_entropy_loss similarity_loss'#'cross_entropy_loss attention_loss'# 'attention_loss'#'ranked_loss cross_entropy_loss'#'cluster_loss cross_entropy_loss'#'cross_entropy_loss'
 MARGIN_RANK: 1.3 ### R: ALPHA - MARGIN_RANK
 ALPHA: 2.0
 TVAL: 1.0
 WEIGHT: 0.4    ### loss: softmax + w*ranked_loss


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 4.Solver
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
SOLVER:
 MAX_EPOCHS: 100
 EVAL_PERIOD: 1
 CHECKPOINT_PERIOD: 1
 LOG_PERIOD: 50
 OUTPUT_DIR: "work_space" 

 # OPTIMIZER configuration
 OPTIMIZER:
  NAME: "Adam"#"SGD"#
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.

 # SCHEDULER configuration
 SCHEDULER:
  BASE_LR: 0.0001#0.001#0.00001#0.0001
  BIAS_LR_FACTOR: 1
  GAMMA: 0.1
  STEPS: [10, 20, 60]#[10, 15, 20]#[3, 6, 9]# [50, 75, 100] #[50, 100, 150]#
  WARMUP_FACTOR: 0.33
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
  LOSS_LR: 0.05
  RETRAIN_FROM_HEAD: 1


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Train Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TRAIN:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Train Transform
 TRANSFORM:
  PROB: 0.0
  RE_PROB: 0.0

 # Train Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4#2

 # Train Trick
 TRICK:
  PRETRAIN_PATH: '.\work_space\pre\densenet121-a639ec97.pth'
  IF_LABELSMOOTH: 'off'#'on'
  PRETRAINED: 1


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Val Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
VAL:
 RE_RANKING: 'no'
 WEIGHT: ""
 FEAT_NORM: 'yes'

 # Val Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4#1

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Specific Setting - Test Configuration
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
TEST:
 RE_RANKING: 'no'
 WEIGHT: "./work_space/mbagnet121_model_37.pth"
 FEAT_NORM: 'yes'

 # Test Dataloader
 DATALOADER:
  CATEGORIES_PER_BATCH: 6
  INSTANCES_PER_CATEGORY_IN_BATCH: 4#3